// Code generated by entimport, DO NOT EDIT.

package schema

import (
	softdelete "go-backend/ent/soft-delete"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Article holds the schema definition for the Article entity.
type Articles struct {
	ent.Schema
}

// Fields of the Article.
func (Articles) Fields() []ent.Field {
	return []ent.Field{
		field.String("title").MaxLen(255),
		field.String("content").Optional().Nillable().StructTag(`json:"content"`),
		field.String("image_url").Optional().Nillable().StructTag(`json:"imageUrl"`),
		field.Int("like_count").Default(0).StructTag(`json:"likeCount"`),
		field.Int("views").Default(0),
		field.Int("user_id").StructTag(`json:"userId"`),

		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
	}
}

// Edges of the Article.
func (Articles) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("Users", Users.Type).Ref("Articles").Field("user_id").Unique().Required(),
	}
}

// Mixin of the Pet.
func (Articles) Mixin() []ent.Mixin {
	return []ent.Mixin{
		softdelete.SoftDeleteMixin{},
	}
}
